### ISSUE TITLE
CSS files with cross-origin don't fetch

### ISSUE THREAD

**Issue by benhatsor** [barhatsor/scepter#1]
Sites that load CSS files with cross-origin don't render in Scepter.  
Or any other `<link>`, for that matter.

**Comment by benhatsor** [comment]
I've found a fix 👀

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#cors-enabled_fetches

Will fix in next update.

**Comment by barhatsor** [comment]
Will fix in next update.
